### ISSUE TITLE
运行结果？

### ISSUE THREAD

**Issue by maomao0220** [C-Xingyu/my_detection#1]
您好，您提供的代码运行之后RVIZ没有结果，我用的kitti数据集，请问是什么原因？您可以提供一下您的数据包吗？

**Comment by maomao0220** [comment]
![111111](https://github.com/C-Xingyu/my_detection/assets/64572122/42f5bb86-75cb-45de-a1ca-0aefbbafc847)
我的终端结果如上图，请问什么原因？

**Comment by C-Xingyu** [comment]
这个可能需要做一些适配工作了，我当时使用的应该是速腾的一款雷达，可能KITTI数据集的数据格式不一样。具体的应该是需要修改代码中数据输入那块，debug一下




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "C-Xingyu/my_detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 晚上8:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [C-Xingyu/my_detection] 运行结果？ (Issue #1)





 

 我的终端结果如上图，请问什么原因？

**Comment by maomao0220** [comment]
我的数据集雷达话题是"/velodyne_points"，也适配了launch文件，运行您的代码时RVIZ可视化依旧没有结果，而且我也查看了输出话题，发现没有消息内容发布，请问怎么解决？期待您的回复 @C-Xingyu
